"""add attempts to otp_codes

Revision ID: 43d5d79794c0
Revises: e4903935859b
Create Date: 2026-09-15 11:22:53.729507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d5d79794c0'
down_revision: Union[str, Sequence[str], None] = 'e4903935859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempts')
    # ### end Alembic commands ###
