"""add monthly_budget and budget_start_day to users

Revision ID: e4903935859b
Revises: f8befb2652da
Create Date: 2026-09-08 15:45:59.860720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4903935859b'
down_revision: Union[str, Sequence[str], None] = 'f8befb2652da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_budget', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('budget_start_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'budget_start_day')
    op.drop_column('users', 'monthly_budget')
    # ### end Alembic commands ###
